name: chairs
favicon: null
layout_spectrum: 0.9801753915380687
typography_spectrum: 0.9251839097123593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27201a'
    - '#d0d3da'
    - '#b7b29e'
    - '#a3928a'
    - '#997c42'
  brandStrength: 0.47408487764187157
  lightness: 0.29832747345790267
  saturation: 0.3308693692088127
  rhythmicContrast: 0.36170277115888894
purpose: []
