typography_spectrum: 1
style: the-composer
color:
  brandColors:
    - '#1f232d'
    - '#71a7ff'
    - '#cde0ff'
    - '#62656c'
    - '#000000'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27894
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nick Jones
  email: nick@narrowdesign.com
  url: 'http://narrowdesign.com'
name: Chairs
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/63832e6e-0f41-4e75-a60e-2a808b01138b.jpg'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
