name: chairs
favicon: null
layout_spectrum: 0.64964
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a3d44'
    - '#ef444a'
    - '#281125'
    - '#fdf1ba'
    - '#a1957d'
  brandStrength: 0
  lightness: 0.29832747345790267
  saturation: 0.3308693692088127
  rhythmicContrast: 1
purpose: []
