name: chairs
favicon: null
layout_spectrum: 0.49622
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2bb673'
    - '#3456d1'
    - '#6d0770'
    - '#8095e2'
    - '#ffffff'
  brandStrength: 0
  lightness: 0.29832747345790267
  saturation: 0.3308693692088127
  rhythmicContrast: 1
purpose: []
