name: chairs
favicon: null
layout_spectrum: 0.50598
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252523'
    - '#fdfcfa'
    - '#807c7b'
    - '#c0b7ae'
    - '#e0ddd8'
  brandStrength: 1
  lightness: 0.29832747345790267
  saturation: 0.3308693692088127
  rhythmicContrast: 0.36170277115888894
purpose: []
